package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/chinese-graph/backend/graph/generated"
	"github.com/chinese-graph/backend/internal/domain"
	"github.com/chinese-graph/backend/internal/repository"
	"github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

// AddWord is the resolver for the addWord field.
func (r *mutationResolver) AddWord(ctx context.Context, input domain.WordInput) (*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	
	word := &domain.Word{
		Hanzi:       input.Hanzi,
		Traditional: input.Traditional,
		Pinyin:      input.Pinyin,
		Meanings:    input.Meanings,
		HSKLevel:    input.HSKLevel,
		Frequency:   1,
	}
	
	if input.Frequency != nil {
		word.Frequency = *input.Frequency
	}
	
	return repo.Create(ctx, word)
}

// UpdateWord is the resolver for the updateWord field.
func (r *mutationResolver) UpdateWord(ctx context.Context, id string, input domain.WordInput) (*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	
	word := &domain.Word{
		ID:          id,
		Hanzi:       input.Hanzi,
		Traditional: input.Traditional,
		Pinyin:      input.Pinyin,
		Meanings:    input.Meanings,
		HSKLevel:    input.HSKLevel,
		Frequency:   1,
	}
	
	if input.Frequency != nil {
		word.Frequency = *input.Frequency
	}
	
	return repo.Update(ctx, word)
}

// DeleteWord is the resolver for the deleteWord field.
func (r *mutationResolver) DeleteWord(ctx context.Context, id string) (bool, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	err := repo.Delete(ctx, id)
	return err == nil, err
}

// AddRelation is the resolver for the addRelation field.
func (r *mutationResolver) AddRelation(ctx context.Context, input domain.RelationInput) (bool, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	err := repo.AddRelation(ctx, &input)
	return err == nil, err
}

// RemoveRelation is the resolver for the removeRelation field.
func (r *mutationResolver) RemoveRelation(ctx context.Context, sourceID string, targetID string, typeArg domain.RelationType) (bool, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeWrite})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	err := repo.RemoveRelation(ctx, sourceID, targetID, typeArg)
	return err == nil, err
}

// MarkReviewed is the resolver for the markReviewed field.
func (r *mutationResolver) MarkReviewed(ctx context.Context, wordID string, correct bool) (*domain.LearningStats, error) {
	// TODO: Implement learning stats tracking
	return &domain.LearningStats{
		WordID:        wordID,
		TimesReviewed: 1,
		CorrectCount:  1,
		Strength:      0.5,
	}, nil
}

// ResetProgress is the resolver for the resetProgress field.
func (r *mutationResolver) ResetProgress(ctx context.Context, wordID string) (bool, error) {
	// TODO: Implement progress reset
	return true, nil
}

// Word is the resolver for the word field.
func (r *queryResolver) Word(ctx context.Context, hanzi string) (*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	return repo.GetByHanzi(ctx, hanzi)
}

// WordByID is the resolver for the wordById field.
func (r *queryResolver) WordByID(ctx context.Context, id string) (*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	repo := repository.NewNeo4jWordRepository(session)
	return repo.GetByID(ctx, id)
}

// WordGraph is the resolver for the wordGraph field.
func (r *queryResolver) WordGraph(ctx context.Context, hanzi string, depth *int, maxNodes *int) (*domain.WordGraph, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	depthVal := 2
	if depth != nil {
		depthVal = *depth
	}
	
	maxNodesVal := 30
	if maxNodes != nil {
		maxNodesVal = *maxNodes
	}

	repo := repository.NewNeo4jWordRepository(session)
	return repo.GetWordGraph(ctx, hanzi, depthVal, maxNodesVal)
}

// SearchWords is the resolver for the searchWords field.
func (r *queryResolver) SearchWords(ctx context.Context, query string, limit *int) ([]*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	limitVal := 20
	if limit != nil {
		limitVal = *limit
	}

	repo := repository.NewNeo4jWordRepository(session)
	return repo.Search(ctx, query, limitVal)
}

// WordsByHsk is the resolver for the wordsByHSK field.
func (r *queryResolver) WordsByHsk(ctx context.Context, level int, limit *int) ([]*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	limitVal := 50
	if limit != nil {
		limitVal = *limit
	}

	repo := repository.NewNeo4jWordRepository(session)
	return repo.GetByHSKLevel(ctx, level, limitVal)
}

// DailyWords is the resolver for the dailyWords field.
func (r *queryResolver) DailyWords(ctx context.Context, count *int, hskLevel *int) ([]*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	countVal := 10
	if count != nil {
		countVal = *count
	}

	repo := repository.NewNeo4jWordRepository(session)
	
	if hskLevel != nil {
		return repo.GetByHSKLevel(ctx, *hskLevel, countVal)
	}
	
	// Return random words for daily practice
	return repo.Search(ctx, "", countVal)
}

// LearningStats is the resolver for the learningStats field.
func (r *queryResolver) LearningStats(ctx context.Context, wordID string) (*domain.LearningStats, error) {
	// TODO: Implement learning stats retrieval
	return &domain.LearningStats{
		WordID:        wordID,
		TimesReviewed: 0,
		CorrectCount:  0,
		Strength:      0.0,
	}, nil
}

// WeakWords is the resolver for the weakWords field.
func (r *queryResolver) WeakWords(ctx context.Context, limit *int) ([]*domain.Word, error) {
	session := r.DB.Session(ctx, neo4j.SessionConfig{AccessMode: neo4j.AccessModeRead})
	defer session.Close(ctx)

	limitVal := 10
	if limit != nil {
		limitVal = *limit
	}

	repo := repository.NewNeo4jWordRepository(session)
	// TODO: Implement weak words based on learning stats
	return repo.Search(ctx, "", limitVal)
}

// WordAdded is the resolver for the wordAdded field.
func (r *subscriptionResolver) WordAdded(ctx context.Context) (<-chan *domain.Word, error) {
	panic(fmt.Errorf("not implemented: WordAdded - wordAdded"))
}

// ProgressUpdated is the resolver for the progressUpdated field.
func (r *subscriptionResolver) ProgressUpdated(ctx context.Context, userID string) (<-chan *domain.LearningStats, error) {
	panic(fmt.Errorf("not implemented: ProgressUpdated - progressUpdated"))
}

// Compounds is the resolver for the compounds field.
func (r *wordResolver) Compounds(ctx context.Context, obj *domain.Word) ([]*domain.WordRelation, error) {
	// TODO: Implement fetching related words
	return []*domain.WordRelation{}, nil
}

// Phrases is the resolver for the phrases field.
func (r *wordResolver) Phrases(ctx context.Context, obj *domain.Word) ([]*domain.WordRelation, error) {
	// TODO: Implement fetching phrases
	return []*domain.WordRelation{}, nil
}

// SimilarWords is the resolver for the similarWords field.
func (r *wordResolver) SimilarWords(ctx context.Context, obj *domain.Word) ([]*domain.WordRelation, error) {
	// TODO: Implement fetching similar words
	return []*domain.WordRelation{}, nil
}

// OppositeWords is the resolver for the oppositeWords field.
func (r *wordResolver) OppositeWords(ctx context.Context, obj *domain.Word) ([]*domain.WordRelation, error) {
	// TODO: Implement fetching opposite words
	return []*domain.WordRelation{}, nil
}

// ComponentOf is the resolver for the componentOf field.
func (r *wordResolver) ComponentOf(ctx context.Context, obj *domain.Word) ([]*domain.WordRelation, error) {
	// TODO: Implement fetching words this is a component of
	return []*domain.WordRelation{}, nil
}

// HasComponents is the resolver for the hasComponents field.
func (r *wordResolver) HasComponents(ctx context.Context, obj *domain.Word) ([]*domain.WordRelation, error) {
	// TODO: Implement fetching component words
	return []*domain.WordRelation{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// Word returns generated.WordResolver implementation.
func (r *Resolver) Word() generated.WordResolver { return &wordResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type wordResolver struct{ *Resolver }